spring.application.name=Backend

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NutritionMarketplace;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=ReplaceWithAtLeast32CharactersSecretKey
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
VNP_TMN_CODE=BVI5EQNF
VNP_HASH_SECRET=I6FB1Q975XMUCAZSFG59ZFCLXTQTPPBW
VNP_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
VNP_RETURN_URL=http://localhost:8000/vnpay-return
