SET IDENTITY_INSERT categories ON;

INSERT INTO categories
(id, name, description, type, status, created_at, updated_at)
VALUES
(1,'Vegetables','Fresh vegetables','PRODUCT',1,GETDATE(),GETDATE()),
(2,'Fruits','Fresh fruits','PRODUCT',1,GETDATE(),GETDATE()),
(3,'Grains','Healthy grains','PRODUCT',1,GETDATE(),GETDATE()),
(4,'Protein','Protein rich foods','PRODUCT',1,GETDATE(),GETDATE()),
(5,'Beverages','Healthy drinks','PRODUCT',1,GETDATE(),GETDATE());

SET IDENTITY_INSERT categories OFF;
SET IDENTITY_INSERT products ON;

INSERT INTO products
(id,seller_id,category_id,name,description,ingredient,nutrition_info,price,image,quantity,status,review_comment,review_date,created_at,updated_at)
VALUES

(1,2,1,
'Organic Broccoli',
'Fresh organic broccoli harvested daily.',
'100% Organic Broccoli',
'Calories:34; Protein:2.8g; Carb:6.6g',
45000,
'https://picsum.photos/seed/product1/600/600',
100,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(2,2,1,
'Fresh Spinach',
'Fresh spinach rich in iron.',
'Organic Spinach',
'Calories:23; Protein:2.9g',
35000,
'https://picsum.photos/seed/product2/600/600',
120,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(3,2,2,
'Organic Apple',
'Sweet imported organic apples.',
'Apple',
'Calories:52; Fiber:2.4g',
80000,
'https://picsum.photos/seed/product3/600/600',
150,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(4,2,2,
'Banana Premium',
'Naturally ripened bananas.',
'Banana',
'Calories:89; Potassium:358mg',
42000,
'https://picsum.photos/seed/product4/600/600',
180,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(5,2,3,
'Brown Rice 1kg',
'Premium whole grain brown rice.',
'100% Brown Rice',
'Calories:111; Protein:2.6g',
68000,
'https://picsum.photos/seed/product5/600/600',
80,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(6,2,3,
'Oatmeal',
'Instant rolled oats.',
'Whole Grain Oats',
'Calories:389; Protein:17g',
95000,
'https://picsum.photos/seed/product6/600/600',
90,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(7,2,4,
'Chicken Breast',
'Lean chicken breast.',
'Fresh Chicken',
'Protein:31g; Fat:3.6g',
135000,
'https://picsum.photos/seed/product7/600/600',
60,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(8,2,4,
'Atlantic Salmon',
'Fresh Atlantic salmon fillet.',
'Salmon',
'Protein:20g; Omega-3',
245000,
'https://picsum.photos/seed/product8/600/600',
45,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(9,2,5,
'Orange Juice',
'Fresh squeezed orange juice.',
'Orange',
'Vitamin C 124mg',
55000,
'https://picsum.photos/seed/product9/600/600',
100,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE()),

(10,2,5,
'Almond Milk',
'Unsweetened almond milk.',
'Almond, Water',
'Calories:30; Calcium',
72000,
'https://picsum.photos/seed/product10/600/600',
75,
'PUBLISHED',
NULL,NULL,
GETDATE(),GETDATE());

SET IDENTITY_INSERT products OFF;